### ISSUE TITLE
Support multiple `TELEGRAM_CHAT_IDs`

### ISSUE THREAD

**Issue by vermaxik** [mustafabayar/immo_trakt#3]
Hi @mustafabayar 

Thank you for a great bot, works like a charm 🤗 

Unfortunately I'm not golang dev, so I can't contribute properly, but I have a feature request to support multiple chat ids. 

It would be much convenient  if my partner and I would receive the same messages together.

Thank you in advance 👍

**Comment by layonez** [comment]
@vermaxik Hey man, you actually can create a group chat with bot and sent messages there :)

**Comment by vermaxik** [comment]
@layonez  didn't know it, will try 🙌  thank you 👍

**Comment by mustafabayar** [comment]
Sorry that I missed this, but glad that you found a solution!
